### ISSUE TITLE
请教一下手机录屏时某些画面或者视频会出现黑屏，这个安卓能知道么

### ISSUE THREAD

**Issue by railsfans** [MagicianGuo/Android-MediaProjectionDemo#1]
请教一下手机录屏时某些画面或者视频会出现黑屏，因为手机安全原因，登陆界面或者版权视频会不允许录制，直接显示黑屏，这个安卓能检测么，我想能在前端提醒用户，这样用户体验更好

**Comment by MagicianGuo** [comment]
这个应该是无法判断的。我在网上看到有种说法，通过 MediaProjectionManager 的 getActiveProjectionInfo 方法返回值（不为空说明能截图），但是这个方法是需要 MANAGE_MEDIA_PROJECTION 权限的，而且这权限只有系统app能获取。所以第三方app应该是做不到的，估计只有root才行

**Comment by railsfans** [comment]
你好，你有没有录屏存文件的demo，我现在在一个项目中遇到一个问题，就是有些手机录制的画质不是很好，调试了基本的几个参数都不管用，不知道你有没有经验分享

**Comment by MagicianGuo** [comment]
> 你好，你有没有录屏存文件的demo，我现在在一个项目中遇到一个问题，就是有些手机录制的画质不是很好，调试了基本的几个参数都不管用，不知道你有没有经验分享

我的最新代码新增了录屏保存文件功能，默认保存到 **/sdcard/Android/data/[包名]** 目录。清晰度的问题可以参考最新代码里面的配置。
