### ISSUE TITLE
投屏问题

### ISSUE THREAD

**Issue by 0cbin** [MagicianGuo/Android-MediaProjectionDemo#2]
投屏是不是还没实现完成

**Comment by MagicianGuo** [comment]
![img](https://github.com/MagicianGuo/Android-MediaProjectionDemo/assets/92171540/1afc14c1-5257-4418-8121-af8c8a978381)
![image](https://github.com/MagicianGuo/Android-MediaProjectionDemo/assets/92171540/90cb0eab-90bd-4b56-9687-0445330e2632)
点击如图所示的按钮，即可显示图中的效果。会将整个屏幕显示的内容投射到一个小窗口上
